- name: nginxplaybook 
  hosts: webservers
  become: true
  
  tasks:
    - name: install docker
      shell: |
        yum install docker
        service docker start
        usermod -a -G docker ec2-user
        newgrp docker
        systemctl enable docker.service
        systemctl start docker.service
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: docker pull & run
      shell: |
        docker rmi adelekegbolahan/nginx-image --force
        docker pull adelekegbolahan/nginx-image:latest
        docker rm nginx_container --force

    - name: run application container
      shell: | 
         docker run -dit --name nginx_container -p 7000:7000 -p 443:443 adelekegbolahan/nginx-image:latest
